[**@ecp.eth/sdk**](../../index.mdx)

***

[@ecp.eth/sdk](/sdk-reference/index.mdx) / [comments](/sdk-reference/comments/index.mdx) / InvalidCommentManagerAddressError

# Class: InvalidCommentManagerAddressError

Defined in: [packages/sdk/src/comments/caip373.ts:50](https://github.com/ecp-eth/comments-monorepo/blob/main/packages/sdk/src/comments/caip373.ts#L50)

Error thrown when the comment manager address is not the same as the chain's comment manager address

## Extends

- [`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx)

## Constructors

### Constructor

```ts
new InvalidCommentManagerAddressError(commentManagerAddress, chainCommentManagerAddress): InvalidCommentManagerAddressError;
```

Defined in: [packages/sdk/src/comments/caip373.ts:51](https://github.com/ecp-eth/comments-monorepo/blob/main/packages/sdk/src/comments/caip373.ts#L51)

#### Parameters

##### commentManagerAddress

`` `0x${string}` ``

##### chainCommentManagerAddress

`` `0x${string}` ``

#### Returns

`InvalidCommentManagerAddressError`

#### Overrides

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`constructor`](/sdk-reference/comments/classes/CAIP373Error.mdx#constructor)

## Properties

### cause?

```ts
optional cause: unknown;
```

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es2022.error.d.ts:26

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`cause`](/sdk-reference/comments/classes/CAIP373Error.mdx#cause)

***

### message

```ts
message: string;
```

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1077

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`message`](/sdk-reference/comments/classes/CAIP373Error.mdx#message)

***

### name

```ts
name: string;
```

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`name`](/sdk-reference/comments/classes/CAIP373Error.mdx#name)

***

### stack?

```ts
optional stack: string;
```

Defined in: node\_modules/.pnpm/typescript@5.8.3/node\_modules/typescript/lib/lib.es5.d.ts:1078

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`stack`](/sdk-reference/comments/classes/CAIP373Error.mdx#stack)

***

### stackTraceLimit

```ts
static stackTraceLimit: number;
```

Defined in: node\_modules/.pnpm/@types+node@22.15.29/node\_modules/@types/node/globals.d.ts:161

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`stackTraceLimit`](/sdk-reference/comments/classes/CAIP373Error.mdx#stacktracelimit)

## Methods

### captureStackTrace()

```ts
static captureStackTrace(targetObject, constructorOpt?): void;
```

Defined in: node\_modules/.pnpm/@types+node@22.15.29/node\_modules/@types/node/globals.d.ts:145

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

##### targetObject

`object`

##### constructorOpt?

`Function`

#### Returns

`void`

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`captureStackTrace`](/sdk-reference/comments/classes/CAIP373Error.mdx#capturestacktrace)

***

### prepareStackTrace()

```ts
static prepareStackTrace(err, stackTraces): any;
```

Defined in: node\_modules/.pnpm/@types+node@22.15.29/node\_modules/@types/node/globals.d.ts:149

#### Parameters

##### err

`Error`

##### stackTraces

`CallSite`[]

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[`CAIP373Error`](/sdk-reference/comments/classes/CAIP373Error.mdx).[`prepareStackTrace`](/sdk-reference/comments/classes/CAIP373Error.mdx#preparestacktrace)
